version: '3.7'
services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:13.2'
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - 'run-build-rule-db:/var/lib/postgresql/data'
  phx:
    image: 'bitwalker/alpine-elixir-phoenix:1.11.3'
    depends_on:
      - db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - '4000:4000'
    volumes:
      - type: bind
        source: .
        target: /opt/app/src
volumes:
  run-build-rule-db: